image: docker:latest

services:
  - docker:dind

before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

build:
    script:
        - docker build -t $CI_REGISTRY/$CI_PROJECT_PATH/c9 .
        - docker tag $CI_REGISTRY/$CI_PROJECT_PATH/c9 $DOCKER_USER/c9
        - docker push $CI_REGISTRY/$CI_PROJECT_PATH/c9
        - docker push $DOCKER_USER/c9

